# Generated by Django 3.0.5 on 2020-05-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20200502_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_question_lists', to='poll.UserProfile'),
            preserve_default=False,
        ),
    ]
