# Generated by Django 3.0.5 on 2020-05-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_questionlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlist',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questionlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Kit',
        ),
        migrations.DeleteModel(
            name='QuestionList',
        ),
    ]
