# Generated by Django 3.0.5 on 2020-05-03 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20200502_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text_answer',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='valid_answer',
            new_name='valid',
        ),
        migrations.AlterField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(related_name='polls', through='poll.Kit', to='poll.Question', verbose_name='Список вопросов'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_polls', to='poll.UserProfile', verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='изображение'),
        ),
    ]
