# Generated by Django 3.0.5 on 2020-05-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_auto_20200504_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='user',
        ),
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.ManyToManyField(null=True, related_name='user_polls', to='poll.UserProfile', verbose_name='пользователь'),
        ),
    ]
