# Generated by Django 3.0.5 on 2020-05-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_auto_20200504_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_polls', to='poll.UserProfile', verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type_user',
            field=models.IntegerField(blank=True, choices=[(1, 'Manager'), (2, 'User')], null=True, verbose_name='тип пользователя'),
        ),
    ]
