# Generated by Django 3.0.5 on 2020-05-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0016_auto_20200504_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit', to='poll.Question'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='polls', through='poll.Kit', to='poll.Question', verbose_name='Список вопросов'),
        ),
    ]
