# Generated by Django 3.0.5 on 2020-05-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_auto_20200505_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitpoll', to='poll.Poll'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitquestion', to='poll.Question'),
        ),
    ]
