# Generated by Django 3.0.5 on 2020-05-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_checkedanswer_checkedpoll_checkedquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedpoll',
            name='admin',
        ),
        migrations.AlterField(
            model_name='checkedpoll',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.Poll', verbose_name='опрос'),
        ),
        migrations.AlterField(
            model_name='checkedpoll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_checked_polls', to='poll.UserProfile', verbose_name='пользователь'),
        ),
    ]
