# Generated by Django 3.0.5 on 2020-05-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0021_auto_20200506_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedanswer',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='checkedanswer',
            name='text',
        ),
        migrations.AddField(
            model_name='checkedanswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_anwers', to='poll.Answer'),
        ),
    ]
