# Generated by Django 3.0.5 on 2020-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0022_auto_20200506_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedanswer',
            name='valid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
