# Generated by Django 3.0.5 on 2020-05-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0024_auto_20200507_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedpoll',
            name='checked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
