# Generated by Django 3.0.5 on 2020-05-09 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0025_checkedpoll_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedanswer',
            name='valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkedquestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_questions', to='poll.Question', verbose_name='вопрос'),
        ),
    ]
