# Generated by Django 3.0.5 on 2020-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0027_checkedquestion_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedpoll',
            name='valid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
