# Generated by Django 3.0.5 on 2020-05-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0028_checkedpoll_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='test',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
