# Generated by Django 3.0.5 on 2020-05-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0030_auto_20200509_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='checked_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='valid_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
