# Generated by Django 3.0.5 on 2020-05-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0033_checkedpoll_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedpoll',
            name='rank',
        ),
        migrations.AddField(
            model_name='poll',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
