# Generated by Django 3.0.5 on 2020-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0035_checkedpoll_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='polls', through='poll.Kit', to='poll.Question', verbose_name='Список вопросов'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_polls', to='poll.UserProfile', verbose_name='пользователь'),
        ),
    ]
