# Generated by Django 3.0.5 on 2020-05-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0040_checkedpoll_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedpoll',
            name='validated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
