# Generated by Django 3.0.5 on 2020-05-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0041_checkedpoll_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedquestion',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
