# Generated by Django 3.0.5 on 2020-05-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0044_auto_20200512_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedpoll',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_poll', to='poll.Poll', verbose_name='опрос'),
        ),
    ]
