# Generated by Django 3.0.5 on 2020-05-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0045_auto_20200512_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='checked_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество отмеченных'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='poll.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=150, verbose_name='текст ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='valid_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество отмеченных верно'),
        ),
    ]
