# Generated by Django 3.0.5 on 2020-05-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0046_auto_20200512_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=150, verbose_name='текст вопроса'),
        ),
    ]
